export const APPLICATION_COLOR = {
    FOOTER_BACKGROUND: "blue",
    HEADER_BACKGROUND: "red",
    NAVIGATION_DROPDOWN_BACKGROUND: "green",
    SIDEBAR_BACKGROUND: "green",
    TEXT_COLOR_DARKEST: "black",
  };
  